name: mtenn
channels:
  - conda-forge
dependencies:
  - pytorch
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - numpy
  - h5py
  - e3nn
  - rdkit
  - ase
  - pydantic >=1.10.8,<2.0.0a0

  # docs
  - sphinx <7.3.6
  - sphinx_rtd_theme
  - pip
  - pip:
    - autodoc_pydantic <2.0.0
